[package]
name = "number_benchmark"
version = "0.1.0"
edition = "2021"
authors = ["ndornseif"]
readme = "README.md"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
